Repository reviewpad/host-event-handler, pull requests merged in 2022-08, with the labels that each got.

#4 feat: add PullRequestReviewEvent github event
  handler/processors.go
Labels: small, run-build

#5 Add unit tests to processor
  Taskfile.yml
  go.mod
  go.sum
  handler/processors_test.go
Labels: large, run-build, show

#6 feat: process issue_comment event
  handler/processors.go
  handler/processors_test.go
Labels: medium, critical, run-build

#7 build: update go-github to v45
  go.mod
  go.sum
  handler/processors.go
  handler/processors_test.go
Labels: small, run-build

#8 feat: process status event
  handler/processors.go
  handler/processors_test.go
Labels: large, critical, run-build

#9 feat: process issues event
  handler/processors.go
  handler/processors_test.go
Labels: small, critical, ship, run-build

#10 feat: process pull request review comment
  handler/processors.go
  handler/processors_test.go
Labels: small, critical, ship, run-build

#12 Extend process event to include detailed event information
  README.md
  handler/processors.go
  handler/processors_test.go
Labels: large, external-contribution, critical, run-build

#13 chore: update reviewpad version
  go.mod
  go.sum
  handler/processors.go
Labels: small, ship, run-build

#14 chore: remove unused code
  go.mod
  handler/processors.go
Labels: small, ship, run-build

#15 refactor: rename EventInfo to TargetEntity
  handler/processors.go
  handler/processors_test.go
Labels: medium, critical, ship, run-build

#16 feat: add owner and repo to target entity
  handler/processors.go
  handler/processors_test.go
Labels: large, external-contribution, run-build
